### PR TITLE
Dashboard -> Creator studio & other

### PR DESCRIPTION
**Pull request by pawelos076232**

### CODE REVIEW

**Comment by zachthedev** [comment]
How can I compile this theme to use in UserStyles?

**Comment by pawelos076232** [comment]
@Zangoran I'm using PHP Storm and this guide should be helpfull:
https://www.jetbrains.com/help/phpstorm/10.0/transpiling-sass-less-and-scss-to-css.html
Compiled code to CSS you can import to your Stylish from: /V4/css/darktube-moz.css

**Comment by pawelos076232** [comment]
However, note that this isn't the only way out. And it's not a complete finite style to publish it on UserStyles

**Comment by zachthedev** [comment]
@pawelos076232 Ok, cool. Thanks for the help!

**Comment by pawelos076232** [comment]
@Zangoran no problem! Good luck!

**Comment by zachthedev** [comment]
@pawelos076232 Quick question. Is the file located in '/V4/css/darktube-moz.css' the already compiled scss? Or do I have to manually compile it myself in PHPStorm?

**Comment by pawelos076232** [comment]
@Zangoran this file is already compiled from SCSS to CSS automatically by File Watcher and ready to go with Stylish ;)

**Comment by zachthedev** [comment]
@pawelos076232 I imported that file into stylish, and it is not working. I even made sure to add the link to apply it to YouTube.

**Comment by pawelos076232** [comment]
@Zangoran huh... idk. This code should work. I tested it yesterday on my laptop and it worked. Only one fact that Stylish display a message about one problem, but it's ok. After import and save it really should work. Maby you paste wrong code? Try this one raw:
https://raw.githubusercontent.com/pawelos076232/DarkTube/master/V4/css/darktube-moz.css

**Comment by zachthedev** [comment]
@pawelos076232 I used the raw one. Which turned out to be different than the one I was using before. But it still isnt working. Let me try a different install of chrome. See if that is the issue.

**Comment by zachthedev** [comment]
@pawelos076232 Trying it in a clean install of chrome did not work either.

**Comment by pawelos076232** [comment]
@Zangoran are you really using import function in Stylish? (The button form the left panel, then you need to click "Overwrite style" button)

**Comment by zachthedev** [comment]
@pawelos076232 I am not importing, I am just copying and pasting the code into the input box. Is that what I should be doing?

**Comment by pawelos076232** [comment]
@Zangoran That's why it's not working. It is in mozilla-format, so you need to use import button

**Comment by zachthedev** [comment]
@pawelos076232 Ahh, that would make sense. My bad. Thanks!

**Pull request closed without merging**
