### PR TITLE
Fixed masthead logo on widths smaller than 704px

### PR DESCRIPTION
**Pull request by ebencollins**
Masthead logo had white edges when the page width was less than 704px. I replaced it with a youtube logo that doesn't have white edges.
Before:
 Before
After:
 After

### CODE REVIEW

**Comment by Nass-O** [comment]
thx, I add it to the v4.

**Comment by ebencollins** [comment]
I added the masthead logo fix to V4 in commit 75521af. 

I think I updated all necessary files.

I also changed the theater-background from black to $bg-darker (this is how you had it in V3. Screenshots below. 

Before: Before
After: After

**Comment by Nass-O** [comment]
thx!

**Comment by ebencollins** [comment]
No problem ;)

**Pull request merged**
